<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IE6CLT7P79VT2" ignored="0" name="TestExtent" tests="3" failures="1" timestamp="22 Sep 2020 06:35:47 GMT" time="0.446" errors="0">
  <testcase name="failTest" time="0.009" classname="org.extentreport.extenttest">
    <failure type="java.lang.AssertionError" message="expected [i] but found [we]">
      <![CDATA[java.lang.AssertionError: expected [i] but found [we]
	at org.extentreport.extenttest.failTest(extenttest.java:32)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase name="passTest" time="0.008" classname="org.extentreport.extenttest"/>
  <testcase name="skiptest" time="0.0" classname="org.extentreport.extenttest">
    <skipped/>
  </testcase> <!-- skiptest -->
</testsuite> <!-- TestExtent -->
